
theme: minima

minima:
  skin: solarized-dark

header_pages:
  - index.md

markdown: kramdown
# plugins:
  # - jekyll-seo-tag

assets:
  features:
    liquid: false


plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'

